### ISSUE TITLE
Response body with array

### ISSUE THREAD

**Issue by low-res** [dingo/blueprint#2]
I have some issues when trying to generate the docs, when my responsebody contains a more complex JSON string. This works:

```
@Response(200, body={"instancetypes":{"id":3,"name":"Wand"}})
```

but:

```
@Response(200, body={"instancetypes":{"id":3,"name":"Wand", "children":[{"id":1}]}})
```

throws the following exception:
 [Doctrine\Common\Annotations\AnnotationException]  
  [Syntax Error] Expected PlainValue, got '[' at position 131 in method App\Http\Controllers\ElementTypeController::showAllSubtypes().

**Comment by jasonlewis** [comment]
Replace the square brackets with curly ones. I know at first it doesn't
look like a JSON string but it'll be encoded into one. This is a limitation
with the annotation parser that I couldn't find a way around and I wasn't
too keen on implementing my own.

**Comment by low-res** [comment]
ok, cheers! This works!
