### ISSUE TITLE
Able to set URI Parameter 'example_value' ?

### ISSUE THREAD

**Issue by bryannielsen** [dingo/blueprint#20]
Hi,

I'm wondering if it's possible to set the `example_value` [documented here](https://github.com/apiaryio/api-blueprint/blob/master/API%20Blueprint%20Specification.md#uri-parameters-section). 

I have looked through the test stubs here and the wiki docs on dingo/api but I'm coming up empty.

**Comment by KoenRijpstra** [comment]
Have you tried to set the example value in the parameter name?

```
/**
 * @Parameters({
 *      @Parameter("id:1", type="integer", required=true description="This is an example.")
 * })
 */
```

**Comment by danjordan** [comment]
This feature would be a useful addition to the wiki on dingo/api. What's the best way to get this added?
