### ISSUE TITLE
Arrays in parameters

### ISSUE THREAD

**Issue by jshah4517** [dingo/blueprint#38]
We have some cases where we have to use arrays as parameters in our API, however it seems these parameters are being discarded when the documentation is being generated.

This is what I have tried so far.

```
@Parameter("attachment[n][filename]", type="string", description="Attachment filename."),
@Parameter("attachment[n][contents]", type="string", description="Base64-encoded file contents."),
```

Is there any way to include this in the generated documentation?

**Comment by timbroder** [comment]
@jshah4517 try { and } in place of [ and ]

**Comment by jshah4517** [comment]
Thanks for the suggestion. I actually realised that it is included but being discarded by the template generating tool we use. Using { and } didn't make a difference, but I'll close this as it doesn't appear to be a problem with this library.
