### ISSUE TITLE
Laravel 5.3 error (not sure if related or not)

### ISSUE THREAD

**Issue by dubcanada** [dingo/blueprint#42]
Hello,

I am running Laravel 5.3 and I keep getting an error when I run `api:docs` I tracked it down to the line

```
protected function getAnnotationByType($type)
{
    return array_first($this->annotations, function ($key, $annotation) use ($type) {
        $type = sprintf('Dingo\\Blueprint\\Annotation\\%s', $type);

        return $annotation instanceof $type;
    });
}
```

If I change the `return $annotation instanceof $type;` to `return $key instanceof $type;` it works perfectly fine, but for me on PHP 7 Laravel 5.3 `$annotation` is equal to a 0 or 1.

Not sure exactly what is up.

**Comment by mmswiderski** [comment]
Hello. 

it's look like Laravel changed default order of values in array_first function: 

> Key / Value Order Change
> 
> The first, last, and where methods on the Arr class now pass the "value" as the first parameter to the given callback Closure. For example:
> 
> Source: https://laravel.com/docs/5.3/upgrade#upgrade-5.3.0

I created a patch that addresses this issue: #44

**Comment by saminanirmala** [comment]
Is this issue solved ?? I am also getting same error

**Comment by MelonSmasher** [comment]
I'm getting this error too.

**Comment by jsdecena** [comment]
So no one from the core is actually looking to fix this?

**Comment by seanmangar** [comment]
This seems to have been merged: https://github.com/dingo/blueprint/pull/44/files/81acaf5159a0447509f71bc17a2ee5732f73de66

**Comment by itsnotvalid** [comment]
@seanmangar merged but still on master. Is any releases planned yet?

**Comment by stojankukrika** [comment]
Can you a release a new version with that code version because it didn't work now, need to be a new version? 
But if you copy that code directly in package, it's works!

**Comment by eness** [comment]
waiting for the master to merge this...

**Comment by hskrasek** [comment]
Tagged 0.2.1 which includes this fix, as well as other adjustments.

**Comment by silasrm** [comment]
Hi @hskrasek,

I'm using dingo/api and dingo/blueprint version is 0.2.2 and this error still exist:

```
➜  git:(master) ✗ php artisan api:docs                    
                                               
  [RuntimeException]                            
  No HTTP method given, invalid API blueprint. 
```
Any solution?

**Comment by purocean** [comment]
@silasrm Try *post* => *Post* and *get* => *Get* and so on. May help you.

**Comment by silasrm** [comment]
Hi @purocean,

Same problem. I change method in annotations like this:
```
// before
/**
     * Return status of API
     *
     * Get a JSON with represetation of status of API
     *
     * @GET("/")
     * @Transaction({
     *      @Request(),
     *      @Response(200, body={"status": "OK"})
     * })
     */

// after
/**
     * Return status of API
     *
     * Get a JSON with represetation of status of API
     *
     * @get("/")
     * @Transaction({
     *      @Request(),
     *      @Response(200, body={"status": "OK"})
     * })
     */
```

I'm wrong?

**Comment by purocean** [comment]
@silasrm use *Get()*

**Comment by silasrm** [comment]
@purocean sorry for delay!
With `Get()` is OK :D 

Thks!
