### ISSUE TITLE
Laravel 5.4

### ISSUE THREAD

**Issue by agentphoenix** [dingo/blueprint#58]
I'm having issues installing the API package because this repo doesn't support Laravel 5.4. Any chance we can get a version that does?

**Comment by pavoltanuska** [comment]
There are already 3 PRs open for this:

- https://github.com/dingo/blueprint/pull/54
- https://github.com/dingo/blueprint/pull/55
- https://github.com/dingo/blueprint/pull/56

We just need to wait for @hskrasek or @jasonlewis to merge it :)

**Comment by agentphoenix** [comment]
Whoops, didn't check the PRs. Sorry about that!

**Comment by pavoltanuska** [comment]
No need to be sorry :)

Meanwhile, if you really need it to run on Laravel 5.4:
- make your own fork of dingo/api
- do the necessary changes (e.g. edit composer.json to require dingo/blueprint in version 0.1.* if you aren't using the stuff from 0.2.*)
- and [require that package from repository](https://getcomposer.org/doc/05-repositories.md#loading-a-package-from-a-vcs-repository)

But don't use that in production (only if you are really sure you can) and keep an eye on the PRs, so you can go back to requiring the official repo, once it's merged.
