### ISSUE TITLE
How can I represent `array[object]` attributes?

### ISSUE THREAD

**Issue by skaic** [dingo/blueprint#71]
I want to write blueprint document like below.

```
+ Request (application/json)

    + Attributes
        + api_token: 1 (number, optional) - The photo id
        + adds (array[object])
            + (object)
                + `a` (string) - adds a
                + `b` (string) - adds b
            
    + Body

            {
                "api_token": "123",
                "adds": [
                    {
                        "a" : "beijing",
                        "b" : "Tian’anmen"
                    }
                ]
            }
```

How do I write this structure of dingo/blueprint?

**Comment by rbochenski** [comment]
This should work:
```
@Attribute("api_token", type="string", sample="123"), 
@Attribute("adds", type="array", sample={{ "a" : "beijing", "b" : "Tian’anmen"}}),
```
Also type here is optional will be deducted from sample.

**Comment by from2day** [comment]
Correct, arrays should be defined with curly brackets {} event though it's not natural :)

**Comment by avlima** [comment]
`@Attribute("adds", type="array", sample={{ "a" : "beijing", "b" : "Tian’anmen"}})`

Not working for me.
Error: Array to string conversion

**Comment by rbochenski** [comment]
please check with that fork: https://github.com/rbochenski/blueprint

add to composer json:
`
    "repositories": [
        {
            "type": "vcs",
            "url": "git@github.com:rbochenski/blueprint.git"
        }
    ],
`
