### ISSUE TITLE
Why this package doesn't support L5.5, 5.6

### ISSUE THREAD

**Issue by mehrdad-shokri** [dingo/blueprint#72]
It's been months since Laravel 5.5 is released and recently L5.6 is released while this package still doesn't support ``illuminate/filesystem`` 5.5 or 5.6?  
I don't know if upgrading from 5.4 to 5.6 requires special consideration, but the act of not updating version number over months gives me the sense of either this project is not actively maintained or maintainers don't care if this package can't be installed on newer versions of Laravel.  
What makes this problem worse it that dingo/API requires this package by default.  
So my question is the reason to delay this much for updating this dependency?  Do they don't have enough time to maintain this repo, or they don't care about newer versions or they use other libs for API developing on Laravel?!

**Comment by rbochenski** [comment]
It looks soon will be released new version.
For now try this fork:
https://github.com/rbochenski/blueprint/releases

**Comment by mehrdad-shokri** [comment]
@rbochenski have submitted a pr, and merged. everything should work now.
