### ISSUE TITLE
Invalid tag v3.0.1

### ISSUE THREAD

**Issue by mnabialek** [dingo/blueprint#85]
It seems one of releases was tagged as 3.0.1 - https://github.com/dingo/blueprint/releases/tag/v3.0.1 and now Packagist shows v3.0.1 as latest version https://packagist.org/packages/dingo/blueprint what causes also invalid info for composer outdated command:

```
composer outdated
dingo/blueprint            v0.4.2 v3.0.1 API Blueprint documentation generator.
```

**Comment by specialtactics** [comment]
Hey there, and thanks for reporting.

I have removed the offending tag, not sure how quick packagist will update, but it should.

**Comment by mnabialek** [comment]
In fact you need to go to Packagist and manually remove tag from it too (you should see x next to tags on right side).

**Comment by specialtactics** [comment]
Unfortunately I don't own the package, so I can not do that.

If it's causing you issues, make sure you set the major version in your composer reqs (which you should be doing anyway).
