### ISSUE TITLE
Is there a contradiction?

### ISSUE THREAD

**Issue by baicaiit** [dingo/blueprint#89]
![image](https://user-images.githubusercontent.com/42630572/114297823-7d946e80-9ae5-11eb-8585-1ea7b80e69c4.png)
dingo/api version 

laravel 5.5 use  phpdocumentor/reflection-docblock is  5 version

so  blueprint v2.x-dev 

![image](https://user-images.githubusercontent.com/42630572/114297846-a0bf1e00-9ae5-11eb-9cf6-fca9ae3bd204.png)

but  illuminate/filesystem: ^7.0|^8.0
illuminate/support: ^7.0|^8.0

**Comment by specialtactics** [comment]
Hey, I am not sure what exactly you are posting but I don't think there is any contradiction.

**Comment by baicaiit** [comment]
> Hey, I am not sure what exactly you are posting but I don't think there is any contradiction.
If you try to install dingo/api in version 5.5 of laravel, you will know the problem.

**Comment by specialtactics** [comment]
@baicaiit This version of laravel is no longer supported (and hasn't been for a long time), but you can still just use an older version of the package.
